### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by summerisgone** [summerisgone/pyphrasy#10]
`virtualenv .env` gives:

```
New python executable in .env/bin/python
Installing setuptools, pip...
  Complete output from command /home/igromov/projec...rasy/.env/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Ignoring indexes: https://pypi.python.org/simple/
Downloading/unpacking setuptools
Downloading/unpacking pip
Installing collected packages: setuptools, pip
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/req.py", line 671, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/req.py", line 901, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/wheel.py", line 140, in move_wheel_files
    scheme = distutils_scheme(name, user=user, home=home, root=root)
  File "/usr/share/python-virtualenv/pip-1.5debian1-py2.py3-none-any.whl/pip/locations.py", line 148, in distutils_scheme
    i = d.get_command_obj('install', create=True)
  File "/usr/lib/python2.7/distutils/dist.py", line 856, in get_command_obj
    self._set_command_options(cmd_obj, options)
  File "/usr/lib/python2.7/distutils/dist.py", line 899, in _set_command_options
    % (source, command_name, option))
DistutilsOptionError: error in setup.cfg: command 'install' has no such option 'single_version_externally_managed'

Storing debug log for failure in /home/igromov/.pip/pip.log
----------------------------------------
...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "/usr/bin/virtualenv", line 3, in <module>
    virtualenv.main()
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 825, in main
    symlink=options.symlink)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 993, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 961, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/usr/lib/python2.7/dist-packages/virtualenv.py", line 903, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/igromov/projec...rasy/.env/bin/python -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 2
```

**Comment by summerisgone** [comment]
@ojomio А это не для тройки ли setup.py?
